### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by juretta** [qiajigou/grma#34]
https://groups.google.com/forum/#!topic/grpc-io/-jQ6lmJt-jc suggests that running Python gRPC in a pre-fork model is not possible.

grma actually seems to somewhat work (in that multiple processes listen on the same socket) but requests are still handled by a single process only in however many threads are configured in the gRPC thread pool. 

I've verified this using lsof and having RPC methods print their thread id and pid.

Have you observed that different processes are actually involved in handling RPC requests?

**Comment by GuoJing** [comment]
Hey, thanks for submitting this issue.

What grma do is just `fork` one gRPC process, make it run multi processes on same port, so it may have better throughput. I think requests should be handled by multi processes. You could check the tools in `benchmark` folder.

In another way, I think, thread pool is a different concept from process. Threads runs in one process, we can't control that (anyway threads in Python is not that good), It's controlled by one gRPC process. What we do is making gRPC server run multi processes on same port.

If tools in benchmark folder not working, @zhongql will help you figure problem out. Or maybe share your code with us will be better I think. 😆
